# Example kubernetes deployment yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: meaty_pythons
spec:
  replicas: 3
  selector:
    matchLabels:
      app: meaty_pythons
  template:
    metadata:
      labels:
        app: meaty_pythons
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
