version: '3.8'

services:
  veggie-gophers-db:
    build: ./veggie-gophers/db
    environment:
      POSTGRES_USER: veggiegophers
      POSTGRES_PASSWORD: password
      POSTGRES_DB: veggiegophers
    volumes:
      - ./veggie-gophers/db/data:/var/lib/postgresql/data
      - ./veggie-gophers/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./veggie-gophers/db/items.csv:/items.csv
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U veggiegophers" ]
      interval: 30s
      timeout: 5s
      retries: 5

  veggie-gophers:
    build: ./veggie-gophers/.
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: postgres://veggiegophers:password@veggie-gophers-db:5432/veggiegophers?sslmode=disable
    depends_on:
      veggie-gophers-db:
        condition: service_healthy
