version: '3.8'

services:
  veggie-gophers-db:
    build: ./veggie-gophers/db
    environment:
      POSTGRES_USER: veggiegophers
      POSTGRES_PASSWORD: password
      POSTGRES_DB: veggiegophers
    volumes:
      - ./veggie-gophers/db/data:/var/lib/postgresql/data
      - ./veggie-gophers/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./veggie-gophers/db/items.csv:/items.csv
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U veggiegophers" ]
      interval: 30s
      timeout: 5s
      retries: 5

  veggie-gophers:
    build: ./veggie-gophers/.
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: postgres://veggiegophers:password@veggie-gophers-db:5432/veggiegophers?sslmode=disable
    depends_on:
      veggie-gophers-db:
        condition: service_healthy

  broker-db:
    build: ./broker/broker-db
    volumes:
      - ./broker/broker-db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootPassword
    ports:
      - 27017:27017
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 10s
      retries: 10

  mongo-seed:
    image: mongo:5.0.3
    volumes:
      - ./broker/broker-db/data.json:/data.json:ro
    command: ["mongoimport", "--host", "broker-db", "-u", "root", "-p", "rootPassword", "--authenticationDatabase", "admin", "--db", "broker", "--collection", "Product", "--type", "json", "--file", "/data.json", "--jsonArray"]
    depends_on:
      - broker-db

  broker:
    build: ./broker
    ports:
      - 8081:8081
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://brokerUser:brokerPassword@broker-db:27017/broker
      VENDOR_URLS: veggie-gophers=http://veggie-gophers:8080/query
    depends_on:
      broker-db:
        condition: service_healthy
      veggie-gophers-db:
        condition: service_healthy
