// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type InventoryItem struct {
	ID         string `json:"id"`
	StockLevel int    `json:"stock_level"`
}

type Vendor struct {
	Title       string           `json:"title"`
	Description string           `json:"description"`
	Icon        string           `json:"icon"`
	Inventory   []*InventoryItem `json:"inventory"`
}
