version: "3.8"

services:
  lambda-market-db:
    build: ./db
    volumes:
      - ./db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      # - ./db/items.json:/items.json:ro
    environment:
      # - MONGO_ROOT_USER=${MONGO_ROOT_USER}
      # - MONGO_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=lambda-market
    ports:
      - 27018:27017
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 5s # TODO: reduce this when we aren't testing
      timeout: 5s
      retries: 5
    networks:
      - backend

  mongo-seed:
    image: mongo:5.0.3
    volumes:
      - ./db/items.json:/items.json:ro
    command:
      [
        "mongoimport",
        "--host",
        "lambda-market-db",
        "-u",
        "${MONGO_ROOT_USER}",
        "-p",
        "${MONGO_ROOT_PASSWORD}",
        "--authenticationDatabase",
        "admin",
        "--db",
        "lambda-market",
        "--collection",
        "Item",
        "--type",
        "json",
        "--file",
        "/items.json",
        "--jsonArray",
        "--upsertFields",
        "classId",
      ]
    depends_on:
      - lambda-market-db
    networks:
      - backend

  mongo-express:
    image: mongo-express:0.54.0
    ports:
      - "8075:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=lambda-market-db
      - ME_CONFIG_MONGODB_PORT=27017
    depends_on:
      lambda-market-db:
        condition: service_healthy
    networks:
      - backend

  lambda-market:
    build: ./service
    ports:
      - "8085:4000"
    depends_on:
      - lambda-market-db
    networks:
      - backend
    environment:
      HOST_DB_URI: mongodb://lambda-market-db:27017
      MONGO_USERNAME: lambdaUser
      MONGO_PASSWORD: lambdaPassword
networks:
  backend:
    driver: bridge
